name: sample
services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: >
      redis-server
      --requirepass myStrongRedisPassword
      --appendonly yes
    restart: unless-stopped

volumes:
  redis_data:

