name: health-application
services:
  vault:
    image: hashicorp/vault:1.19
    container_name: vault
    ports:
      - "8100:8100"
    environment:
      VAULT_ADDR: http://0.0.0.0:8100
      VAULT_API_ADDR: http://localhost:8100
      VAULT_LOCAL_CONFIG: |
        {
          "storage": {
            "consul": {
              "address": "health-application-consul-1:8500",
              "path": "vault/"
            }
          },
          "listener": [{
            "tcp": {
              "address": "0.0.0.0:8100",
              "tls_disable": 1
            }
          }],
          "default_lease_ttl": "168h",
          "max_lease_ttl": "720h",
          "ui": true
        }
    cap_add:
      - IPC_LOCK
    healthcheck:
      test: [ "CMD", "vault", "status" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - vault_data:/vault/file

volumes:
  vault_data:
